FROM node:16.13.0-alpine AS build

WORKDIR /app

COPY . .

RUN npm ci && npm run build

FROM nginx:alpine AS frontend

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/cloud-drive-frontend /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
